#!/bin/zsh --no-rcs

setopt errexit

user=$(/usr/bin/stat -f %Su /dev/console)
downloads=~$user/Downloads
dock_apps=(
    "/System/Applications/Apps.app"
    "/Applications/Google Chrome.app"
    "/Applications/Microsoft Word.app"
    "/Applications/Microsoft PowerPoint.app"
    "/Applications/Microsoft Excel.app"
    "/Applications/Microsoft Outlook.app"
    "/Applications/Microsoft OneNote.app"
    "/Applications/Microsoft Teams.app"
    "/Applications/Managed Software Center.app"
    "/System/Applications/System Settings.app"
)

run_as_user() {
    /bin/launchctl asuser "$(/usr/bin/id -u "$user")" /usr/bin/sudo -u "$user" "$@"
}

run_as_user /usr/bin/defaults write com.apple.dock persistent-apps -array \
    '<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>'${^dock_apps}'</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>'
run_as_user /usr/bin/defaults write com.apple.dock persistent-others -array \
    "<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>$downloads</string><key>_CFURLStringType</key><integer>0</integer></dict><key>file-label</key><string>Downloads</string><key>file-type</key><string>2</string></dict><key>tile-type</key><string>directory-tile</string></dict>"
run_as_user /usr/bin/defaults write com.apple.dock show-recents -bool false
run_as_user /usr/bin/defaults write com.apple.dock minimize-to-application -bool true
run_as_user /usr/bin/killall -KILL Dock || true

run_as_user /usr/bin/osascript -l JavaScript -e 'ObjC.import("AppKit"); $.NSWorkspace.sharedWorkspace.setDesktopImageURLForScreenOptionsError($.NSURL.fileURLWithPath("/Library/Desktop Pictures/Woodleigh.jpg"), $.NSScreen.mainScreen, $({}), null)' || true
