apiVersion: stemma/v1alpha1
kind: Project
metadata:
  name: woodleigh-catalog
spec:
  components:
    mac-software:
      destinations:
        woodstar:
          pkginfo:
            supported_architectures:
              - arm64
          retention:
            keep: 1
          targets:
            exclude: []
            include: []
    windows-win32:
      destinations:
        intune:
          allowedArchitectures: x64
          installExperience:
            deviceRestartBehavior: basedOnReturnCode
            runAsAccount: system
          minimumSupportedWindowsRelease: Windows11_24H2
          retention:
            keep: 1
          returnCodes:
            - returnCode: 0
              type: success
            - returnCode: 1707
              type: success
            - returnCode: 3010
              type: softReboot
            - returnCode: 1641
              type: hardReboot
            - returnCode: 1618
              type: retry
          type: win32
  destinations:
    intune:
      config:
        client_id: ${INTUNE_CLIENT_ID}
        client_secret: ${INTUNE_CLIENT_SECRET}
        tenant_id: ${INTUNE_TENANT_ID}
      operation: intune
    woodstar:
      config:
        api_key: ${WOODSTAR_API_KEY}
        url: https://woodstar.woodleigh.vic.edu.au
      operation: woodstar.munki
  imports:
    - software/**/*.yaml
  plugins:
    woodstar:
      path: plugins/woodstar
      trusted: true
