apiVersion: stemma/v1alpha1
kind: Project
metadata:
  name: woodleigh-catalog
spec:
  components:
    mac-software:
      destinations:
        woodstar:
          pkginfo:
            supported_architectures:
              - arm64
          retention:
            keep: 1
          targets:
            exclude: []
            include: []
  destinations:
    woodstar:
      config:
        api_key: ${WOODSTAR_DEV_API_KEY}
        url: https://woodstar:8443
      operation: woodstar.munki
  imports:
    - software/**/buildmacpkg.yaml
    - software/**/macsoftware.yaml
  plugins:
    woodstar:
      path: plugins/woodstar
      trusted: true
  reconcile:
    source_control:
      type: github
      config:
        client_id: ${GITHUB_APP_CLIENT_ID}
        installation_id: ${GITHUB_APP_INSTALLATION_ID}
        private_key: ${GITHUB_APP_PRIVATE_KEY}
