# yaml-language-server: $schema=https://raw.githubusercontent.com/woodleighschool/stemma-catalog/main/stemma.schema.json
apiVersion: stemma/v1alpha1
kind: Project
metadata:
  name: woodleigh-catalog
spec:
  components:
    mac-software:
      destinations:
        woodstar:
          retention:
            keep: 1
    windows-win32:
      destinations:
        intune:
          architecture: x64
          install_experience:
            restart: based_on_return_code
            run_as: system
          minimum_windows_release: Windows11_24H2
          retention:
            keep: 1
          return_codes:
            - code: 0
              type: success
            - code: 1707
              type: success
            - code: 3010
              type: soft_reboot
            - code: 1641
              type: hard_reboot
            - code: 1618
              type: retry
  destinations:
    intune:
      config:
        client_id: "{{ env.INTUNE_CLIENT_ID }}"
        client_secret: "{{ env.INTUNE_CLIENT_SECRET }}"
        tenant_id: "{{ env.INTUNE_TENANT_ID }}"
      operation: intune
    woodstar:
      config:
        api_key: "{{ env.WOODSTAR_API_KEY }}"
        url: https://woodstar.woodleigh.vic.edu.au
      operation: woodstar.munki
  imports:
    - software/**/*.yaml
  plugins:
    downloads:
      image: ghcr.io/woodleighschool/stemma-catalog/downloads:0.2.1@sha256:eaf90b3ed90012ca7f0e9d902829797fbde5011df1ae2966e093f4f69c912bc6
      trusted: true
    woodstar:
      image: ghcr.io/woodleighschool/woodstar/stemma@sha256:9c0af2b397eb7e212b8d3602cab1879790588dbdf770a1db5e9159c199eb41c2
      trusted: true
  reconcile:
    source_control:
      type: github
      config:
        client_id: "{{ env.GITHUB_APP_CLIENT_ID }}"
        installation_id: "{{ env.GITHUB_APP_INSTALLATION_ID }}"
        private_key: "{{ env.GITHUB_APP_PRIVATE_KEY }}"
