# yaml-language-server: $schema=https://raw.githubusercontent.com/woodleighschool/stemma-catalog/main/stemma.schema.json
apiVersion: stemma/v1alpha1
kind: MacSoftware
metadata:
  name: windows-app
spec:
  extends: mac-software
  source:
    resolver: microsoft
    product: windows-app
  application:
    bundle_id: com.microsoft.rdc.macos
    installed_path: /Applications/Windows App.app
  signature:
    signer: apple:developer-id:UBF8T346G9 # Microsoft Corporation
  icon: windows-app
  destinations:
    woodstar:
      pkginfo:
        category: Productivity
        description: Windows App (formerly Microsoft Remote Desktop) is your gateway to Azure
          Virtual Desktop, Windows 365, Microsoft Dev Box, Remote Desktop Services, and remote PCs,
          securely connecting you to Windows devices and apps.
        developer: Microsoft
        name: Windows App
        unattended_install: true
        unattended_uninstall: true
        uninstall_method: removepackages
        uninstallable: true
      targets:
        include:
          - label_name: All Staff
            actions:
              - optional_installs
              - managed_updates
        exclude: []
