# yaml-language-server: $schema=https://raw.githubusercontent.com/woodleighschool/stemma-catalog/main/stemma.schema.json
apiVersion: stemma/v1alpha1
kind: MacSoftware
metadata:
  name: penbank-campus-printers
spec:
  extends: mac-software
  minimum_os: "11.0"
  icon: printers
  destinations:
    woodstar:
      pkginfo:
        blocking_applications: []
        category: Printing
        description: Adds the Penbank Campus print queue.
        developer: Woodleigh School
        installcheck_script: |-
          #!/bin/zsh --no-rcs

          /usr/bin/lpstat -p penbank_campus &> /dev/null && exit 1
          exit 0
        installer_type: nopkg
        name: Penbank Campus Printers
        postinstall_script: |-
          #!/bin/zsh --no-rcs

          /usr/sbin/lpadmin -p penbank_campus -E \
              -v lpd://pc-printserver.woodleighschool.net/PCPQ \
              -P "/Library/Printers/PPDs/Contents/Resources/EPSON AM-C6000 Series.gz" \
              -D "Penbank Campus" \
              -L "Penbank Campus" \
              -o printer-is-shared=false \
              -o EPIJ_Bidi_Com=0 \
              -o EPIJ_FUnt=2 \
              -o EPIJ_Fnsr=4 \
              -o EPIJ_OptFUnit=2 \
              -o EPIJ_PUnt=2
        requires:
          - EPSON Drivers
        unattended_install: true
        unattended_uninstall: true
        uninstall_method: uninstall_script
        uninstall_script: |-
          #!/bin/zsh --no-rcs

          if /usr/bin/lpstat -p penbank_campus &> /dev/null; then
              /usr/sbin/lpadmin -x penbank_campus
          fi
        uninstallable: true
        version: "1.2"
      targets:
        include:
          - label_name: Penbank Campus
            actions:
              - managed_installs
          - label_name: All Hosts
            actions:
              - optional_installs
        exclude: []
