# yaml-language-server: $schema=https://raw.githubusercontent.com/woodleighschool/stemma-catalog/main/stemma.schema.json
apiVersion: stemma/v1alpha1
kind: MacSoftware
metadata:
  name: 1password
spec:
  extends: mac-software
  source:
    url: https://downloads.1password.com/mac/1Password.pkg
  application:
    bundle_id: com.1password.1password
    installed_path: /Applications/1Password.app
  signature:
    signer: apple:developer-id:2BUA8C4S2C # AgileBits Inc.
  icon: 1password
  destinations:
    woodstar:
      pkginfo:
        category: Security
        description: 1Password makes it easy to generate, store, and autofill passwords for all your
          online accounts, on all your devices. Because weak and reused passwords are a leading
          cause of security incidents, using a password manager is an easy way to protect yourself,
          your family, or your business.
        developer: AgileBits Inc.
        name: 1Password
        unattended_install: true
        unattended_uninstall: true
        uninstall_method: removepackages
        uninstallable: true
      targets:
        include:
          - label_name: All Staff
            actions:
              - optional_installs
              - managed_updates
        exclude: []
