# yaml-language-server: $schema=https://raw.githubusercontent.com/woodleighschool/stemma-catalog/main/stemma.schema.json
apiVersion: stemma/v1alpha1
kind: MacSoftware
metadata:
  name: dante-controller
spec:
  extends: mac-software
  source:
    resolver: audinate
    product: dante-controller
  package_path: DanteController.pkg
  application:
    path: DanteController.pkg/Payload/Dante Controller.app
    installed_path: /Applications/Dante Controller.app
  signature:
    signer: apple:developer-id:P4WCR6Y822 # Audinate Pty Ltd
  destinations:
    woodstar:
      pkginfo:
        category: Utilities
        description: >-
          Dante Controller provides essential device status information and
          powerful real-time network monitoring, including device-level latency
          and clock stability stats, multicast bandwidth usage, and customized
          event logging, enabling you to quickly identify and resolve any
          potential network issues. You can also quickly and easily backup,
          restore, move, and reuse Dante network configurations using Presets,
          and edit Dante routing configurations offline.
        developer: Audinate
        name: Dante Controller
        unattended_install: true
        uninstall_method: removepackages
        uninstallable: true
      targets:
        include:
          - label_name: All Hosts
            actions:
              - optional_installs
        exclude: []
