# yaml-language-server: $schema=https://raw.githubusercontent.com/woodleighschool/stemma-catalog/main/stemma.schema.json
apiVersion: stemma/v1alpha1
kind: MacSoftware
metadata:
  name: docker-desktop
spec:
  extends: mac-software
  source:
    resolver: homebrew
    cask: docker-desktop
  application:
    bundle_id: com.docker.docker
  signatures:
    - subject:
        path: Docker.app
      signer: apple:developer-id:9BNSXJN65R # Docker Inc
  icon: docker-desktop
  destinations:
    woodstar:
      pkginfo:
        blocking_applications:
          - Docker Desktop
        category: Developer Tools
        description: Docker Desktop is collaborative containerization software for developers.
        developer: Docker
        name: Docker Desktop
        postinstall_script: |-
          #!/bin/zsh --no-rcs

          /Applications/Docker.app/Contents/MacOS/install --accept-license --user="$(/usr/bin/stat -f %Su /dev/console)"
        postuninstall_script: |-
          #!/bin/zsh --no-rcs

          /bin/rm -rf \
              "/Library/Application Support/com.docker.docker" \
              /Library/LaunchDaemons/com.docker.{socket,vmnetd}.plist \
              /Library/Logs/com.docker.dockerd.log \
              "/Library/Logs/Docker Desktop" \
              /Library/PrivilegedHelperTools/com.docker.{hyperkit,socket,vmnetd} \
              /private/var/run/docker.sock \
              /private/var/tmp/com.docker.vmnetd.socket \
              /usr/local/bin/{docker,docker-compose,hyperkit,kubectl,kubectl.docker,vpnkit} \
              /usr/local/bin/docker-credential-{desktop,ecr-login,osxkeychain}
        preinstall_script: |-
          #!/bin/zsh --no-rcs

          [[ $(/usr/bin/stat -f %Su /dev/console) != root ]]
        preuninstall_script: |-
          #!/bin/zsh --no-rcs

          /Applications/Docker.app/Contents/MacOS/uninstall
          /Applications/Docker.app/Contents/MacOS/install remove-kube-host
          /Applications/Docker.app/Contents/MacOS/install remove-socket-symlink-on-startup
          /Applications/Docker.app/Contents/MacOS/install remove-vmnetd
          exit 0
        unattended_install: true
        unattended_uninstall: true
        uninstall_method: remove_copied_items
        uninstallable: true
      targets:
        include:
          - label_name: All Hosts
            actions:
              - optional_installs
              - managed_updates
        exclude: []
