# yaml-language-server: $schema=https://raw.githubusercontent.com/woodleighschool/stemma-catalog/main/stemma.schema.json
apiVersion: stemma/v1alpha1
kind: MacSoftware
metadata:
  name: garageband
spec:
  extends: mac-software
  source:
    path: /Applications/GarageBand.app
  application:
    installed_path: "/Applications/GarageBand.app"
  destinations:
    woodstar:
      pkginfo:
        category: Creativity
        description: GarageBand is Apple's music creation studio for recording, playing,
          and producing music.
        developer: Apple
        name: GarageBand
        unattended_install: true
        unattended_uninstall: true
        uninstall_method: remove_copied_items
        uninstallable: true
      targets:
        include:
          - label_name: All Hosts
            actions:
              - optional_installs
              - managed_updates
        exclude: []
