# yaml-language-server: $schema=https://raw.githubusercontent.com/woodleighschool/stemma-catalog/main/stemma.schema.json
apiVersion: stemma/v1alpha1
kind: MacSoftware
metadata:
  name: godot
spec:
  extends: mac-software
  source:
    url: https://godotengine.org/download/macos/
    match: https://downloads\.godotengine\.org/\?version=4\.[0-9.]+&flavor=stable&slug=macos\.universal\.zip&platform=macos\.universal
  application:
    path: Godot.app
    bundle_id: org.godotengine.godot
  signature:
    signer: apple:developer-id:6K46PWY5DM # Prehensile Tales B.V.
  icon: godot
  destinations:
    woodstar:
      pkginfo:
        category: Programming
        description: >-
          Godot is a free and open-source game development engine for 2D and 3D games,
          with a scene and node structure that can be extended with GDScript.
        developer: Godot Foundation
        name: Godot
        unattended_install: true
        unattended_uninstall: true
        uninstallable: true
      targets:
        include:
          - label_name: All Hosts
            actions:
              - optional_installs
              - managed_updates
        exclude: []
