# yaml-language-server: $schema=https://raw.githubusercontent.com/woodleighschool/stemma-catalog/main/stemma.schema.json
apiVersion: stemma/v1alpha1
kind: MacSoftware
metadata:
  name: minecraft-education
spec:
  extends: mac-software
  source:
    url: https://aka.ms/meeclientmacos
  application:
    path: minecraft-edu.app
    bundle_id: com.microsoft.minecraft-edu
  signature:
    signer: apple:developer-id:UBF8T346G9 # Microsoft Corporation
  icon: minecraft-education
  destinations:
    woodstar:
      pkginfo:
        category: Education
        description: Engage students in game-based learning across the curriculum. Minecraft
          Education is a game-based platform that inspires creative, inclusive learning through
          play. Explore blocky words that unlock new ways to take on any subject or challenge.
        developer: Microsoft
        name: Minecraft Education
        unattended_install: true
        unattended_uninstall: true
        uninstall_method: remove_copied_items
        uninstallable: true
      targets:
        include:
          - label_name: Minecraft Education Licence
            actions:
              - optional_installs
              - managed_updates
          - label_name: All Staff
            actions:
              - optional_installs
              - managed_updates
        exclude: []
