# yaml-language-server: $schema=https://raw.githubusercontent.com/woodleighschool/stemma-catalog/main/stemma.schema.json
apiVersion: stemma/v1alpha1
kind: MacSoftware
metadata:
  name: munki
spec:
  source:
    resolver: github
    repository: munki/munki
    asset: munkitools-*.pkg
  application:
    bundle_id: com.googlecode.munki.ManagedSoftwareCenter
    installed_path: "/Applications/Managed Software Center.app"
  signature:
    signer: apple:developer-id:T4SK8ZXCXG # Mac Admins Open Source
  minimum_os: "11.0"
  icon: munki
  destinations:
    intune:
      display_name: Munki
      description: >-
        Munki is a set of tools that, used together with a webserver-based  repository of packages and package metadata, can be used by macOS  administrators to manage software installs (and in many cases removals)  on macOS client machines.
      publisher: Mac Admins Open Source
      ignore_version_detection: false
      included_apps:
        - id: "{{ evidence['macos.application'].app.bundle_id }}"
          version: "{{ evidence['macos.application'].app.version }}"
      assignments:
        - intent: required
          all_devices: true
      retention:
        keep: 1
