# yaml-language-server: $schema=https://raw.githubusercontent.com/woodleighschool/stemma-catalog/main/stemma.schema.json
apiVersion: stemma/v1alpha1
kind: MacSoftware
metadata:
  name: pages
spec:
  extends: mac-software
  source:
    path: /Applications/Pages Creator Studio.app
  application:
    installed_path: "/Applications/Pages Creator Studio.app"
  destinations:
    woodstar:
      pkginfo:
        blocking_applications:
          - Pages
        category: Productivity
        description: Pages is Apple's word processor for creating documents and collaborating
          with others.
        developer: Apple
        name: Pages
        preinstall_script: |-
          #!/bin/zsh --no-rcs

          /bin/rm -rf "/Applications/Pages.app"
        unattended_install: true
        unattended_uninstall: true
        uninstall_method: remove_copied_items
        uninstallable: true
      targets:
        include:
          - label_name: All Hosts
            actions:
              - optional_installs
              - managed_updates
        exclude: []
