# yaml-language-server: $schema=https://raw.githubusercontent.com/woodleighschool/stemma-catalog/main/stemma.schema.json
apiVersion: stemma/v1alpha1
kind: MacSoftware
metadata:
  name: santa
spec:
  extends: mac-software
  source:
    resolver: github
    repository: northpolesec/santa
    asset: santa-*.pkg
  application:
    path: app.pkg/Payload/var/db/santa/migration/Santa.app
    version_key: CFBundleVersion
    installed_path: "/Applications/Santa.app"
  signature:
    signer: apple:developer-id:ZMCG7MLDV9 # North Pole Security, Inc.
  destinations:
    woodstar:
      pkginfo:
        blocking_applications: []
        category: Security
        description: Santa is a binary and file access authorization system for macOS.
          It consists of a system extension that monitors for executions and file
          access.
        developer: North Pole Security
        name: Santa
        unattended_install: true
      targets:
        include:
          - label_name: All Hosts
            actions:
              - managed_installs
        exclude: []
