# yaml-language-server: $schema=https://raw.githubusercontent.com/woodleighschool/stemma-catalog/main/stemma.schema.json
apiVersion: stemma/v1alpha1
kind: MacSoftware
metadata:
  name: sketchup-2026
spec:
  extends: mac-software
  source:
    url: https://sketchup.trimble.com/sketchup/2026/SketchUpPro-dmg
    filename: SketchUp2026.dmg
    headers:
      User-Agent: Mozilla/5.0
  application:
    path: SketchUp 2026/SketchUp.app
    installed_path: /Applications/SketchUp 2026/SketchUp.app
  signature:
    signer: apple:developer-id:J8PVMCY7KL # Trimble Inc.
  destinations:
    woodstar:
      pkginfo:
        blocking_applications:
          - SketchUp
          - LayOut
        category: STEAM
        description: >-
          SketchUp is 3D modelling software for designing, documenting, and
          communicating ideas.
        developer: Trimble
        items_to_copy:
          - destination_path: /Applications
            source_item: SketchUp 2026
        name: SketchUp 2026
        unattended_install: true
        unattended_uninstall: true
        uninstall_method: remove_copied_items
        uninstallable: true
      targets:
        include:
          - label_name: All Hosts
            actions:
              - optional_installs
              - managed_updates
        exclude: []
