# yaml-language-server: $schema=https://raw.githubusercontent.com/woodleighschool/stemma-catalog/main/stemma.schema.json
apiVersion: stemma/v1alpha1
kind: MacSoftware
metadata:
  name: visual-studio-code
spec:
  extends: mac-software
  source:
    url: https://code.visualstudio.com/sha/download?build=stable&os=darwin-arm64-dmg
  application:
    path: Visual Studio Code.app
    bundle_id: com.microsoft.VSCode
    installed_path: /Applications/Visual Studio Code.app
  signature:
    signer: apple:developer-id:UBF8T346G9 # Microsoft Corporation
  icon: visual-studio-code
  destinations:
    woodstar:
      pkginfo:
        blocking_applications:
          - Visual Studio Code.app
        category: Programming
        description: >-
          Visual Studio Code is a code editor redefined and optimized for building
          and debugging modern web and cloud applications.
        developer: Microsoft
        name: Visual Studio Code
        postinstall_script: |-
          #!/bin/bash
          mkdir -p /usr/local/bin || exit 1
          ln -sf "/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code" /usr/local/bin/code
        postuninstall_script: |-
          #!/bin/bash
          rm -f /usr/local/bin/code
        unattended_install: true
        unattended_uninstall: true
        uninstall_method: remove_copied_items
        uninstallable: true
      targets:
        include:
          - label_name: All Hosts
            actions:
              - optional_installs
              - managed_updates
        exclude: []
