# yaml-language-server: $schema=https://raw.githubusercontent.com/woodleighschool/stemma-catalog/main/stemma.schema.json
apiVersion: stemma/v1alpha1
kind: BuildMacPkg
metadata:
  name: garageband-all-sounds
spec:
  inputs:
    assets:
      path: Assets
    scripts:
      path: Scripts
  scripts:
    postinstall:
      $input: scripts
      path: all-sounds-postinstall
    loopdown:
      $input: assets
      path: loopdown
    loopdown-LICENSE.txt:
      $input: assets
      path: loopdown-LICENSE.txt
  package:
    identifier: au.edu.vic.woodleigh.garageband-all-sounds
    version: 2.0.3.1
---
apiVersion: stemma/v1alpha1
kind: BuildMacPkg
metadata:
  name: garageband-essential-sounds
spec:
  inputs:
    assets:
      path: Assets
    scripts:
      path: Scripts
  scripts:
    postinstall:
      $input: scripts
      path: essential-sounds-postinstall
    loopdown:
      $input: assets
      path: loopdown
    loopdown-LICENSE.txt:
      $input: assets
      path: loopdown-LICENSE.txt
  package:
    identifier: au.edu.vic.woodleigh.garageband-essential-sounds
    version: 2.0.3.2
