# yaml-language-server: $schema=https://raw.githubusercontent.com/woodleighschool/stemma-catalog/main/stemma.schema.json
apiVersion: stemma/v1alpha1
kind: WindowsSoftware
metadata:
  name: zoom
spec:
  extends: windows-win32
  source:
    url: https://zoom.us/client/latest/ZoomInstallerFull.msi?archType=x64
  signature:
    signer: authenticode:dabb2081eb1d52bf60d812d955f60279629167729ab8fd13708b0f66502e4795 # Zoom Communications, Inc.
  destinations:
    intune:
      display_name: Zoom Workplace
      description: Zoom Workplace for Windows.
      publisher: Zoom Communications, Inc.
