# yaml-language-server: $schema=https://raw.githubusercontent.com/woodleighschool/stemma-catalog/main/stemma.schema.json
apiVersion: stemma/v1alpha1
kind: BuildMacPkg
metadata:
  name: logi-options-plus
spec:
  inputs:
    vendor:
      url: https://download01.logi.com/web/ftp/pub/techsupport/optionsplus/logioptionsplus_installer_offline.zip
  signatures:
    - input: vendor
      subject:
        path: logioptionsplus_installer_offline.app
      signer: apple:developer-id:QED4VVPZWA
  scripts:
    postinstall: |-
      #!/bin/bash
      set -eu
      directory="$(/usr/bin/dirname "$0")/installer"
      "$directory/logioptionsplus_installer_offline.app/Contents/MacOS/logioptionsplus_installer" --quiet
    installer:
      $input: vendor
      path: .
  package:
    identifier: com.github.woodleighschool.pkg.LogiOptionsPlus
    version: "{{ inputs.vendor.facts['logioptionsplus_installer_offline.app'].app.build }}"
