# yaml-language-server: $schema=https://raw.githubusercontent.com/woodleighschool/stemma/refs/heads/main/stemma.schema.json
apiVersion: stemma/v1alpha1
kind: MacSoftware
metadata:
  name: microsoft-edge
spec:
  application:
    bundle_id: com.microsoft.edgemac
    installed_path: /Applications/Microsoft Edge.app
  destinations:
    woodstar:
      pkginfo:
        blocking_applications:
          - Microsoft AutoUpdate
          - Microsoft Edge
          - Microsoft Error Reporting
        category: Productivity
        description: Get Microsoft Edge, your AI-powered browser, and explore a smarter way to
          browse, find, create and do beyond what you ever thought possible.
        developer: Microsoft
        name: Microsoft Edge
        unattended_install: true
        unattended_uninstall: true
        uninstall_method: removepackages
        uninstallable: true
      targets:
        exclude: []
        include:
          - actions:
              - optional_installs
            label_name: All Hosts
  extends: mac-software
  icon: microsoft-edge
  signature:
    signer: apple:developer-id:UBF8T346G9 # Microsoft Corporation
  source:
    url: https://go.microsoft.com/fwlink/?linkid=2093504
