# yaml-language-server: $schema=https://raw.githubusercontent.com/woodleighschool/stemma/refs/heads/main/stemma.schema.json
apiVersion: stemma/v1alpha1
kind: WindowsSoftware
metadata:
  name: google-chrome
spec:
  destinations:
    intune:
      description: Google Chrome Enterprise for Windows.
  extends: windows-win32
  signature:
    signer: authenticode:4a6519d3c145fc3838df20b3009980fe59b9bc68ee5871e59aaa0097a523e333 # Google LLC
  source:
    url: https://dl.google.com/dl/chrome/install/googlechromestandaloneenterprise64.msi
