# yaml-language-server: $schema=https://raw.githubusercontent.com/woodleighschool/stemma/refs/heads/main/stemma.schema.json
apiVersion: stemma/v1alpha1
kind: MacSoftware
metadata:
  name: company-portal
spec:
  application:
    bundle_id: com.microsoft.CompanyPortalMac
    installed_path: /Applications/Company Portal.app
  destinations:
    woodstar:
      pkginfo:
        category: Productivity
        description: The Company Portal provides access to corporate apps and resources from almost
          any network. Your company must already subscribe to Microsoft Intune, and your IT admin
          must set up your account before you can use this app.
        developer: Microsoft
        name: Company Portal
        unattended_install: true
        uninstallable: false
      targets:
        exclude: []
        include:
          - actions:
              - optional_installs
              - managed_updates
            label_name: All Hosts
  extends: mac-software
  icon: company-portal
  signature:
    signer: apple:developer-id:UBF8T346G9 # Microsoft Corporation
  source:
    resolver: microsoft
    product: company-portal
