# yaml-language-server: $schema=https://raw.githubusercontent.com/woodleighschool/stemma-catalog/main/stemma.schema.json
apiVersion: stemma/v1alpha1
kind: MacSoftware
metadata:
  name: woodleigh-fonts
suspend: true
spec:
  destinations:
    woodstar:
      pkginfo:
        category: Fonts
        description: >-
          Woodleigh School managed font bundle.
        developer: Woodleigh
        name: Woodleigh Fonts
        unattended_install: true
      targets:
        exclude: []
        include:
          - actions:
              - managed_installs
            label_name: All Hosts
  extends: mac-software
  source:
    resource:
      kind: BuildMacPkg
      name: woodleigh-fonts
      output: installer
