monorepo_root = true

[env]
_.file = ["{{config_root}}/.env"]
STEMMA_CACHE_DIR = "{{ config_root }}/.stemma/cache"

[tools]
oxfmt = "0.67.0"

[settings]
experimental = true
pin = true
lockfile = true

[monorepo]
config_roots = ["plugins/*"]
