# yaml-language-server: $schema=https://raw.githubusercontent.com/woodleighschool/stemma-catalog/main/stemma.schema.json
apiVersion: stemma/v1alpha1
kind: BuildMacPkg
metadata:
  name: adobe-creative-cloud
spec:
  inputs:
    vendor:
      url: https://helpx.adobe.com/download-install/apps/download-install-apps/creative-cloud-apps/download-creative-cloud-desktop-app-using-direct-links.html
      match: https://ccmdls\.adobe\.com/AdobeProducts/StandaloneBuilds/ACCC/ESD/[0-9.]+/[0-9.]+/macarm64/ACCCx[0-9_]+\.dmg
      headers:
        User-Agent: Go-http-client/1.1
  signatures:
    - input: vendor
      subject:
        path: Install.app
      signer: apple:developer-id:JQ525L2MZD # Adobe Inc.
  scripts:
    postinstall: |-
      #!/bin/sh
      exec "$(/usr/bin/dirname "$0")/installer/Install.app/Contents/MacOS/Install" --mode=silent
    installer:
      $input: vendor
      path: .
  package:
    identifier: com.github.woodleighschool.pkg.AdobeCreativeCloud
    version: "{{ inputs.vendor.filename.replace('ACCCx', '').replace('.dmg', '').replace('_', '.') }}"
