# yaml-language-server: $schema=https://raw.githubusercontent.com/woodleighschool/stemma-catalog/main/stemma.schema.json
apiVersion: stemma/v1alpha1
kind: WindowsSoftware
metadata:
  name: vivi
spec:
  extends: windows-win32
  source:
    url: https://api.vivi.io/windows-msi64
  signatures:
    - subject:
        path: .
      signer: authenticode:e117afa2fa737e283c9613a90de10923364c5f6dfe8323711bb3fd6e920c9794 # Vivi International Pty Ltd
  icon: vivi
  destinations:
    intune:
      display_name: Vivi
      description: Vivi is the only scalable, easy-to-use wireless screensharing and student
        engagement platform engineered for, and by, the education sector. Any device, any number of
        users or classrooms, any media type, any learning type, any display.
      publisher: &publisher Vivi
      developer: *publisher
      detection:
        - type: registry
          key: HKEY_LOCAL_MACHINE\SOFTWARE\Vivi Corporation\Vivi
          value_name: Version
          property: version
      assignments:
        - intent: required
          all_devices: true
