# yaml-language-server: $schema=https://raw.githubusercontent.com/woodleighschool/stemma/refs/heads/main/stemma.schema.json
apiVersion: stemma/v1alpha1
kind: MacSoftware
metadata:
  name: vernier-graphical-analysis
spec:
  application:
    bundle_id: Vernier.GraphicalAnalysis
    installed_path: /Applications/Vernier Graphical Analysis.app
    path: Vernier Graphical Analysis.app
  destinations:
    woodstar:
      pkginfo:
        category: Education
        description: Vernier Graphical Analysis pairs with sensors to let students collect,
          visualise, and analyse lab data directly on their Mac.
        developer: Vernier
        name: Vernier Graphical Analysis
        unattended_install: true
        unattended_uninstall: true
        uninstall_method: remove_copied_items
        uninstallable: true
  extends: mac-software
  signature:
    signer: apple:developer-id:75WN2B2WR8 # Vernier Software & Technology
  source:
    url: https://software-releases.graphicalanalysis.com/ga/mac/release/latest/Vernier-Graphical-Analysis.dmg
