#!/bin/zsh --no-rcs
setopt errexit

here=${0:A:h}
state_dir="/Library/Application Support/Woodleigh/GarageBandAllSounds"
manifests=(/Applications/GarageBand.app/Contents/Resources/garageband<->.plist(n))
manifest=${manifests[-1]:t}

/usr/bin/curl --fail --location --silent --show-error --compressed \
    --output "$here/$manifest" \
    "https://audiocontentdownload.apple.com/lp10_ms3_content_2016/$manifest"
/usr/bin/plutil -lint "$here/$manifest" >/dev/null

"$here/loopdown" deploy --app garageband --core --optional --cache-server auto

/usr/bin/install -d -m 0755 "$state_dir"
/usr/bin/install -m 0644 "$here/$manifest" "$state_dir/$manifest"
