# yaml-language-server: $schema=https://raw.githubusercontent.com/woodleighschool/stemma/refs/heads/main/stemma.schema.json
apiVersion: stemma/v1alpha1
kind: MacSoftware
metadata:
  name: nap-locked-down-browser
spec:
  application:
    bundle_id: au.com.janison.mac.naplan
    installed_path: /Applications/NAP Locked down browser.app
  destinations:
    woodstar:
      pkginfo:
        blocking_applications:
          - NAP Locked down browser
          - NAP Locked down browser Uninstaller
        category: Education
        description: The NAP Locked down browser lets students securely participate in NAPLAN and
          NAP Sample tests by preventing access to other applications and unauthorised device
          resources during an assessment.
        developer: ACARA
        minimum_os_version: "14.0"
        name: NAP Locked down browser
        requires:
          - software: rosetta
        unattended_install: true
        unattended_uninstall: true
        uninstall_method: removepackages
        uninstallable: true
      targets:
        exclude: []
        include:
          - actions:
              - managed_installs
            label_name: SAC MacBooks
          - actions:
              - managed_installs
            label_name: NAPLAN Students
  extends: mac-software
  icon: nap-locked-down-browser
  signature:
    signer: apple:developer-id:KU9HRE5GET # Janison
  source:
    match: https://[^"\s]+\.pkg
    url: https://www.assessform.edu.au/naplan-online/locked-down-browser
